### ISSUE TITLE
java.lang.NullPointerException when running server

### ISSUE THREAD

**Issue by T3rr0or** [Sunderw3k/Pillow#2]
java.lang.NullPointerException
	at rip.sunrise.server.config.Config.load(Config.kt:30)
	at rip.sunrise.server.config.Config.<init>(Config.kt:15)
	at rip.sunrise.server.MainKt.main(Main.kt:22)
	at rip.sunrise.server.MainKt.main(Main.kt)
Starting HTTP Server
Starting Netty Server

**Comment by Sunderw3k** [comment]
`scriptConfigDirectory` doesn't exist. (either the file or the config key). I have to add meaningful messages there.

**Comment by T3rr0or** [comment]
I don't think i fully understand. do i make that?

**Comment by T3rr0or** [comment]
I have set the CONFIG_DIR and put the config.json in it

**Comment by Sunderw3k** [comment]
Does your `config.json` point to a valid directory, like in the readme? Does the folder exist?

**Comment by T3rr0or** [comment]
Ahh no.. where should it point to?

**Comment by T3rr0or** [comment]
![image](https://github.com/user-attachments/assets/734e49e6-6e5b-41c0-a4c4-160092506694)

**Comment by Sunderw3k** [comment]
Try doing the client stuff first, get a script you want from their website and download it like it says in the readme. That generates all the required files and you just need to set configDir to the `./output/configs/`

**Comment by T3rr0or** [comment]
How do you just "Download the script" i can only press + on them to add them

**Comment by Sunderw3k** [comment]
Click try on a paid one and run the `client` jar. That will download it.

**Comment by T3rr0or** [comment]
Damn thats cool. i think the readme could use a update tho

**Comment by Sunderw3k** [comment]
I made the repo today lool, but yeah I could probably mention how to actually get the scripts. Didn't think about it because of how many times I did it.

**Comment by T3rr0or** [comment]
okay so i downloaded it and now run the server with the files in the config_dir?

**Comment by Sunderw3k** [comment]
Point the `scriptConfigDirectory` to the generated `configs`

**Comment by T3rr0or** [comment]
like this? {
    "revisionFile": "revision.txt",
    "scriptConfigDir": "C:\\Users\\xsvl\\IdeaProjects\\Pillow\\output",
    "serverUrl": "http://localhost:6666/"
}

**Comment by Sunderw3k** [comment]
`output/configs`, but I'm not sure if that will work. Copy everything from `output` to the directory you're running the jar from and just do `.../Pillow/configs`.

**Comment by T3rr0or** [comment]
okay the server works and the game starts but i dont get support role

**Comment by T3rr0or** [comment]
![image](https://github.com/user-attachments/assets/b7f6d189-30ac-4950-9c2a-54d577dc1c52)

**Comment by T3rr0or** [comment]
11:40:22 PM: [INFO] Your current rank(s):
	[MEMBERS]

**Comment by T3rr0or** [comment]
Fixed TY!

**Comment by T3rr0or** [comment]
getting this error now: C:\Users\xsvl\.jdks\corretto-21.0.5\bin\java.exe -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -jar C:\Users\xsvl\Desktop\Pillow\client\build\libs\client-0.0.1-all.jar
Connecting to DreamBot servers.
Open
Nov 07, 2024 12:40:17 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.io.FilesKt__FileReadWriteKt.writeText, parameter text
	at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt)
	at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:140)
	at rip.sunrise.client.ClientHandler.writeRevisionData(ClientHandler.kt:104)
	at rip.sunrise.client.ClientHandler.channelRead(ClientHandler.kt:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1473)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1336)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1385)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Scripts owned: 3
Exception in thread "Thread-0" kotlin.UninitializedPropertyAccessException: lateinit property scriptSession has not been initialized
	at rip.sunrise.client.ClientHandler.channelRead$lambda$1(ClientHandler.kt:60)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by T3rr0or** [comment]
i think they fixed it

**Comment by Sunderw3k** [comment]
Added more info in [9c948a4](https://github.com/Sunderw3k/Pillow/commit/9c948a42298ae19d63a111fc124503d1c383fe17) and [e385aba](https://github.com/Sunderw3k/Pillow/commit/e385aba92aabce0f06003872f4515e044118cec6)
